### ISSUE TITLE
Banner that references github issues to provide notebook status

### ISSUE THREAD

**Issue by zachbogart** [zachbogart/huh-data#2]
Wanting a way to signal the status of a notebook right off the rip. Adding to #1 

Notes

This can be a way to "Set a way to define when still working on a notebook in Observable". Things like: 
-  Need to be able to get at quickly for myself
- Need to signal to viewer that this is a work in progress

Maybe
Modify Observable note to specify color, use as indicator for notebook status

**Comment by zachbogart** [comment]
I added this functionality, built out ability to get info on repos from GitHub API. The banner works, but it can get rate limited. I added an "emergency banner" that tries to deal with this, but I don't love it. May revisit.
- https://observablehq.com/d/f9f23b5f41e7ca68

**Comment by zachperiscopic** [comment]
Could be nice for the link to the github issue to open in a new tab.
