### ISSUE TITLE
Cheat at Digits

### ISSUE THREAD

**Issue by zachbogart** [zachbogart/huh-data#21]
Notebook for solving new game from the NYT called [Digits](https://www.nytimes.com/games/digits).

---

This was a fun one! Worked out the general approach on my window and it was pretty seamless. Had some troubles getting the recursion to work, had to check for the solution. I'm sure there's room for improvement, but went quite well right out of the gate!

Process:
- Find all permutations of number pairs (realized this was necessary in approach since subtraction and division have and order)
- Apply a math operation to a pair and get a result (check if valid)
- Recursively solve on the smaller number set (more combos, math operations, etc.) till the number set contains the solution
- Return the steps and present as a table

![IMG-7963](https://user-images.githubusercontent.com/31786233/232259339-ed52c6dc-99b8-4147-afb4-22dd185049e3.JPG)

**Comment by zachbogart** [comment]
I'm excited to see where this game goes. It is currently available as a public beta through NYT and I encourage you to checkout [the Games Team's post on creating new games](https://www.nytimes.com/2023/04/10/crosswords/games-digits-beta.html). 

I wouldn't recommend using this notebook to actually cheat at Digits every day. That misses the point. Instead, it was a cool example for me to try out some coding skills and apply them to the genre of puzzles. It certainly comes from a place of love. I'm a big puzzles fan—pencil, jigsaw, or otherwise—and I encourage you to give this one a go. Flexes your mental math chops. 

Till next time!

**Comment by davpla** [comment]
Hi, Zach.  I enjoyed seeing your solution to this puzzle.  I think you used depth-first search, right.  It's most likely to find solutions with many steps.  I used breadth-first search.  It finds the shortest solution.  I wrote it in Haskell, my favorite programming language.  
![image](https://github.com/zachbogart/huh-data/assets/819261/8f872b0d-2325-49c2-a9cd-69efa663b0cf)

**Comment by zachbogart** [comment]
Hi there! Awesome to see your solution! Certainly looks cleaner than my code. 

Yes, I'd say my approach is basically depth-first, and I like your approach for finding the shortest solution. Have been interested in thinking about this puzzle in terms like this, finding the "best solution" not just getting the right answer.

Thanks for sharing!
